---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/
- docs/
- docs_src/
