language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"

#sudo: required

addons:
  apt:
    packages:
    - mosquitto

services:
  - mongodb
  - mosquitto
#  - rabbitmq

#before_script: mosquitto

# command to run tests
script: nosetests
