language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"

services:
  - mongodb
  - rabbitmq

#addons:
#  apt:
#    packages:
#    - mosquitto
#
#before_script: mosquitto

# command to run tests
script: nosetests
