language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  apt:
    packages:
    - mosquitto

# command to run tests
script: nosetests
